DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Models/SubService.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Services_Booking_System.Models
{
    public class SubService
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "SubService Name")]
        public string SubServiceName { get; set; }
        [Required]
        [Display(Name = "SubService Image")]
        public string SubServiceImage { get; set; }
        [Required]
        public int Price { get; set; }

        public int ServiceId { get; set; }
        public Service Service { get; set; }
    }
}

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Controllers/SubServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services_Booking_System.Models;
using Services_Booking_System.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Vereyon.Web;

namespace Services_Booking_System.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SubServicesController : Controller
    {
        private readonly ISubServiceRepository _subserviceRepo;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IServiceRepository _serviceRepo;
        private readonly IFlashMessage flashMessage;
        public SubServicesController(ISubServiceRepository subServiceRepo, IHostingEnvironment hostingEnvironment, IServiceRepository serviceRepo, IFlashMessage flashMessage)
        {

            _subserviceRepo = subServiceRepo;
            this.hostingEnvironment = hostingEnvironment;
            _serviceRepo = serviceRepo;
            this.flashMessage = flashMessage;
        }
        public IActionResult Index()
        {
            var services = _serviceRepo.GetServices();
            ViewData["ServiceId"] = new SelectList(services, "Id", "ServiceName");
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult List(int Serviceid)
        {
            var model = _subserviceRepo.GetSubServicesOfService(Serviceid);
            ViewData["SelectedService"] = _serviceRepo.GetService(Convert.ToInt32(Serviceid)).ServiceName;
            return View(model);
        }
        [HttpPost]
        public IActionResult List(IFormCollection form)
        {

            //return Convert.ToInt32(form["SelectedService"]);
            if (form != null)
            {
                var model = _subserviceRepo.GetSubServicesOfService(Convert.ToInt32(form["SelectedService"]));
                ViewData["SelectedService"] = _serviceRepo.GetService(Convert.ToInt32(form["SelectedService"])).ServiceName;
                return View(model);
            }

            return View();
        }
        [HttpGet]
        public ViewResult Create()
        {
            var services = _serviceRepo.GetServices();
            ViewData["ServiceId"] = new SelectList(services, "Id", "ServiceName");
            return View();
        }

        [HttpPost]

        public IActionResult Create(SubServiceCreateViewModel model)
        {
            if (ModelState.IsValid)
            {

                string uniqueFileName = null;
                if (model.SubServiceImage != null)
                {
                    string uploadFolder = Path.Combine(hostingEnvironment.WebRootPath, "SubServiceImages");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.SubServiceImage.FileName;
                    string filePath = Path.Combine(uploadFolder, uniqueFileName);
                    model.SubServiceImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                SubService newSubService = new SubService
                {
                    SubServiceName = model.SubServiceName,
                    SubServiceImage = uniqueFileName,
                    Price = model.Price,
                    ServiceId = model.ServiceId
                };
                _subserviceRepo.Add(newSubService);
                flashMessage.Confirmation("SubService Added Successfully");
                return RedirectToAction("Details", new { id = newSubService.Id });
            }
            return View();
        }

        public ViewResult Details(int id)
        {
            SubService Subservice = _subserviceRepo.GetSubService(id);
            if (Subservice == null)
            {
                Response.StatusCode = 404;
                return View("SubServiceNotFound", id);
            }
            return View(Subservice);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            SubService Subservice = _subserviceRepo.GetSubService(id);
            if (Subservice == null)
            {
                return NotFound();
            }
            return View(Subservice);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var Subservice = _subserviceRepo.GetSubService(id);
            _subserviceRepo.Delete(Subservice.Id);
            flashMessage.Danger("SubService Deleted Successfully");
            return RedirectToAction("Index");
        }

        [HttpGet]

        public ViewResult Edit(int id)
        {
            SubService Subservice = _subserviceRepo.GetSubService(id);
            SubServiceEditViewModel subServiceEditViewModel = new SubServiceEditViewModel
            {
                ExitstingPhotoPath = Subservice.SubServiceImage,
                Id = Subservice.Id,
                SubServiceName = Subservice.SubServiceName,
                Price = Subservice.Price,
                ServiceId = Subservice.ServiceId

            };
            var services = _serviceRepo.GetServices();
            ViewData["ServiceId"] = new SelectList(services, "Id", "ServiceName");
            //SubService subService = _subserviceRepo.GetSubService(id);
            return View(subServiceEditViewModel);
        }

        [HttpPost]

        public IActionResult Edit(SubServiceEditViewModel model)
        {
            //ViewBag.IsPostBack = IsPost();
            var services = _serviceRepo.GetServices();
            ViewData["ServiceId"] = new SelectList(services, "Id", "ServiceName");
            if (ModelState.IsValid)
            {
                SubService subService = _subserviceRepo.GetSubService(model.Id);
                subService.SubServiceName = model.SubServiceName;
                subService.Price = model.Price;
                subService.ServiceId = model.ServiceId;

                if (model.SubServiceImage != null)
                {
                    if (model.ExitstingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "SubServiceImages", model.ExitstingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    subService.SubServiceImage = ProcessUploadedFile(model);

                }
                SubService updatedService = _subserviceRepo.Update(subService);
                flashMessage.Confirmation("SubService Updated Successfully");
                //ModelState.AddModelError("success", "Updated sucessfully");
                return RedirectToAction("Index");
            }
            //else
            //{
            //    ModelState.AddModelError("success", string.Empty);
            //}

            return View(model);
        }
        private bool IsPost()
        {
            return HttpContext.Request.Method == "POST";
        }
        private string ProcessUploadedFile(SubServiceEditViewModel model)
        {
            string uniqueFileName = null;
            if (model.SubServiceImage != null)
            {
                string uploadFolder = Path.Combine(hostingEnvironment.WebRootPath, "SubServiceImages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.SubServiceImage.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.SubServiceImage.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/Create.cshtml
@model Services_Booking_System.ViewModels.SubServiceCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">

                <label asp-for="SubServiceName" class="col-sm-7 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="SubServiceName" class="form-control" />
                    <span asp-validation-for="SubServiceName" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="SubServiceImage" class="col-sm-5 control-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="SubServiceImage" class="form-control custom-file-input" />
                        <label class="custom-file-label">Choose File...</label>
                    </div>

                </div>

            </div>
            <div class="form-group row">

                <label asp-for="Price" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-10">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

            </div>
            <div class="form-group row">
                <label asp-for="ServiceId" class="col-sm-4 col-form-label"></label>
                <div class="col-sm-10">
                    <select asp-for="ServiceId" class="form-control" asp-items="ViewBag.ServiceId"></select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/Delete.cshtml
@model Services_Booking_System.Models.SubService

@{
    ViewData["Title"] = "Delete";
    var PhotoPath = "/SubServiceImages/" + Model.SubServiceImage;
}

@*<h1>Delete</h1>*@

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sub Service</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubServiceName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SubServiceName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SubServiceImage)
        </dt>
        <dd class="col-sm-10">
            <img src="@PhotoPath" width="200px" asp-append-version="true" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Service)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Service.ServiceName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/Details.cshtml
@model Services_Booking_System.Models.SubService

@{
    ViewData["Title"] = "Details";
    var PhotoPath = "/SubServiceImages/" + Model.SubServiceImage;
}

<h1>Details</h1>
<flash dismissable="true" />
<div class="row justify-content-center m-3">
    <div class="col-sm-8">
        <div class="card" style="margin-left:200px;min-width:18rem;max-width:30.5%;">

            <div class="card-header text-center">
                <h3>@Html.DisplayFor(model => model.SubServiceName)</h3>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top" style="width:200px;height:200px" src="@PhotoPath" asp-append-version="true" />
            </div>
            <div class="text-center">
                <h4> &#8377; @Model.Price</h4>
                <small>@Model.Service.ServiceName</small>
            </div>
            <div class="card-footer text-center">
                <a asp-action="Edit" class="btn btn-primary m-1" asp-route-id="@Model.Id">Edit</a> |
                <a asp-action="Delete" class="btn btn-danger m-1" asp-route-id="@Model.Id">Delete</a>
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/Edit.cshtml
@model Services_Booking_System.ViewModels.SubServiceEditViewModel
@using System.Net.Http;

@{
    ViewData["Title"] = "Edit";
    var IsPostBack = ViewBag.IsPostBack;
    var PhotoPath = "/SubServiceImages/" + Model.ExitstingPhotoPath;
}

<h1>Edit</h1>

<h4>Service</h4>
<hr />
<div class="row">
    <div class="col-md-4">

        @*@if (!ViewData.ModelState.IsValid && ViewData.ModelState["success"].Errors.Count > 0 && !ViewData.ModelState["success"].Errors.First().ErrorMessage.ToString().Equals(""))
        {
            <div class="alert alert-success">
                @ViewData.ModelState["success"].Errors.First().ErrorMessage
            </div>
        }*@
        <form asp-action="Edit" asp-controller="SubServices" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ExitstingPhotoPath" />
            <div class="form-group">
                <label asp-for="SubServiceName" class="control-label"></label>
                <input asp-for="SubServiceName" class="form-control" />
                <span asp-validation-for="SubServiceName" class="text-danger"></span>
            </div>
            <div class="form-group row">
                <label asp-for="SubServiceImage" class="col-sm-5 control-label"></label>
                <div class="col-sm-10">
                    <div class="custom-file">
                        <input asp-for="SubServiceImage" class="form-control custom-file-input" />
                        <label class="custom-file-label">Click here to change photo</label>
                    </div>

                </div>

            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <select asp-for="ServiceId" class="form-control" asp-items="ViewBag.ServiceId"></select>
            </div>
            <div class="form-group col-sm-4 offset-4">
                <img src="@PhotoPath" width=200px asp-append-version="true" />
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" value="Update" class="btn btn-primary">Update</button>
                    <a asp-action="index" asp-controller="SubServices" class="btn btn-primary">Cancel</a>
                </div>
            </div>
            @section Scripts {
                <script>
                    $(document).ready(function () {
                        $('.custom-file-input').on("change", function () {
                            var fileName = $(this).val().split("\\").pop();
                            $(this).next('.custom-file-label').html(fileName);
                        });
                    });
                </script>
            }
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@*@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/Index.cshtml
@model Services_Booking_System.Models.SubService
@{
    ViewData["Title"] = "Index";

}

@*<h1>Index</h1>*@
<flash dismissable="true" />
<p>
    <a asp-action="Create">Create New Subservice</a>
</p>
<div class="row">
    <div class="col-md-4">
        @*@if ( ViewData.ModelState["success"].Errors.Count > 0)
            {
                <div class="alert alert-success">@ViewData.ModelState["success"].Errors.First().ErrorMessage
                </div>
            }*@
        <form method="post" asp-action="List">
            <div class="form-group row">
                <label asp-for="ServiceId" class="col-sm-4 col-form-label">Service Name</label>

                <div class="col-sm-10">
                    @Html.DropDownList("SelectedService", (IEnumerable<SelectListItem>)ViewData["ServiceId"], new { @class = "form-control" })
                    @*<select asp-for="ServiceId" class="form-control" id="SelectedService" asp-items="ViewBag.ServiceId"></select>*@
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" value="View Subservices" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/SubServices/List.cshtml
@model IEnumerable<Services_Booking_System.Models.SubService>
@inject SignInManager<ApplicationUser> signinManager;
@{
    ViewData["Title"] = "Index";

}

<h1>@ViewData["SelectedService"]</h1>
@if (Model.Count() == 0)
{
    <div>No sub services found!</div>
    <br />
    @if (signinManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <a asp-action="Create">Create New SubService</a>
    }
}
else
{
    <div class="card-deck">
        @foreach (var item in Model)
        {
            var PhotoPath = "/SubServiceImages/" + item.SubServiceImage;
            <div class="card m-3 " style="min-width:18rem;max-width:30.5%;">
                <div class="card-header text-center ">
                    <h3>@item.SubServiceName</h3>
                </div>
                <div class="card-body text-center">
                    <img class="card-img-top" style="width:200px" src="@PhotoPath" asp-append-version="true" />

                </div>
                <div class="text-center">
                    <h4> &#8377; @item.Price</h4>
                </div>
                <div class="card-footer text-center">
                    @if (!signinManager.IsSignedIn(User) || (signinManager.IsSignedIn(User) && !User.IsInRole("Admin")))
                    {
                        <a asp-action="Book" asp-controller="Booking" class="btn btn-primary m-1" asp-route-id="@item.Id">Book</a>
                    }
                    @if (signinManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" class="btn btn-primary m-1" asp-route-id="@item.Id">Edit</a>
                        @*<a asp-action="Details" class="btn btn-success m-1" asp-route-id="@item.Id">Details</a>*@
                        <a asp-action="Delete" class="btn btn-danger m-1" asp-route-id="@item.Id">Delete</a>
                    }

                </div>
            </div>

        }
    </div>
}
<div>
    @if (signinManager.IsSignedIn(User) && User.IsInRole("Admin"))
    {
        <a asp-action="Index">Back to List</a>
    }
    else
    {
        <a asp-action="Index" asp-controller="Home">Back to List</a>
    }
</div>