DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Controllers/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services_Booking_System.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Vereyon.Web;

namespace Services_Booking_System.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StaffController : Controller
    {
        private readonly IStaffRepository _staffRepo;
        private readonly IServiceRepository _serviceRepo;
        private readonly IFlashMessage flashMessage;
        public StaffController(IStaffRepository staffRepo, IServiceRepository serviceRepo, IFlashMessage flashMessage)
        {
            _staffRepo = staffRepo;
            _serviceRepo = serviceRepo;
            this.flashMessage = flashMessage;
        }
        public IActionResult Index()
        {
            var model = _staffRepo.GetAllStaffs();
            return View(model);
        }
        [AllowAnonymous]
        [HttpGet]
        public ViewResult Create()
        {
            var services = _serviceRepo.GetServices();
            ViewData["ServiceId"] = new SelectList(services, "Id", "ServiceName");
            return View();
        }
        [AllowAnonymous]

        [HttpPost]
        public IActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                Staff newDpt = _staffRepo.Add(staff);
                flashMessage.Confirmation("We will get back to you !");
                return RedirectToAction("index","home");
            }
            flashMessage.Danger("Please apply again!");
            return View();
        }

        public ViewResult Details(int id)
        {
            Staff staff = _staffRepo.GetStaff(id);
            if (staff == null)
            {
                Response.StatusCode = 404;
                return View("StaffNotFound", id);
            }
            return View(staff);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Staff staff = _staffRepo.GetStaff(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var staff = _staffRepo.GetStaff(id);
            _staffRepo.Delete(staff.Id);
            flashMessage.Danger("Deleted successfully");
            return RedirectToAction("Index");
        }
    }
}

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}
<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

DotNetCoreMVCProject_CE089_CE092/Services_Booking_System/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signinManager;
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Service_booking_system</title>

    <link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Services Booking System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<ul class="navbar-nav flex-grow-1 ml-auto ">

                        </ul>*@
                    <div class="collapse navbar-collapse" id="collapsibleNavbar">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @*If the user is signed-in display Logout link*@
                            @if (signinManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Booking" asp-action="GetBookings">
                                        Past Bookings
                                    </a>
                                </li>
                            }
                            @if (!signinManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="account" asp-action="register">
                                        Register
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="account" asp-action="login">
                                        Login
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Create">Apply as Professional</a>
                                </li>
                            }


                            @*@if (Context.Session.GetString("Role")!=null && Context.Session.GetString("Role").Equals("Admin"))*@
                            @if (signinManager.IsSignedIn(User) && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Booking" asp-action="GetBookingsAdmin">
                                        Bookings
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="administration" asp-action="index">
                                        Admin
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="SubServices" asp-action="Index">SubServices</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Staff Applications</a>
                                </li>

                            }
                            &emsp;
                            @if (signinManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <form method="post" asp-controller="account" asp-action="logout">
                                        <button type="submit" style="width:auto"
                                                class="nav-link text-dark">
                                            Logout @User.Identity.Name
                                        </button>
                                    </form>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Service_booking_system - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>